######################################################################
# Automatically generated by qmake (3.0) mar. mai 20 15:10:37 2014
######################################################################

QT += widgets

TEMPLATE = app
TARGET = dipylon
INCLUDEPATH += .

# Input
HEADERS = sourceeditor.h \
          commentaryeditor.h \
          mainsplitter.h 

SOURCES += main.cpp \
           sourceeditor.cpp \
           commentaryeditor.cpp \
           mainsplitter.cpp
